<?php

namespace App\Tests\Service;

use App\Entity\Table;
use App\Service\TableService;
use PHPUnit\Framework\TestCase;
use Symfony\Component\Validator\Validator\ValidatorInterface;

class TableServiceTest extends TestCase
{
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testValidateTable() {
        $table = new Table();
        $table ->setPlace('1');
        $table -> setTitle('test');

        $validator = $this->getMockBuilder(ValidatorInterface::class)
           ->getMock();
        
        $tableService = new TableService($validator);
    }

}